# Fill in {{ my_cluster }} before applying this yaml to your kuul k8s cluster.
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ my_cluster }}-ro
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: kuul-cr1
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "namespaces"]
  verbs: ["get", "describe", "list"]

- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "describe", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kuul-crb1
  namespace: default
subjects:
- kind: ServiceAccount
  name: {{ my_cluster }}-ro
  namespace: default
roleRef:
  kind: ClusterRole
  name: kuul-cr1
  apiGroup: rbac.authorization.k8s.io
